# Generated by Django 4.0.10 on 2024-08-21 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='subtitles',
            new_name='subtitle',
        ),
    ]
